version: '3'

services:
  front:
    image: node:alpine3.18
    tty: true
    working_dir: /frontend
    volumes:
      - './frontend:/frontend'
    ports:
      - "3006:3000"

  backend:
    image: jupyter/pyspark-notebook
    container_name: pyspark_notebook
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - ./backend:/home/jovyan/work
    environment:
      - PYSPARK_PYTHON=/usr/bin/python3
      - PYSPARK_DRIVER_PYTHON=ipython3
      - GRANT_SUDO=yes
      - NB_GID=100
      - GEN_CERT=yes
    user: root



